export enum IconType {
  LOGO = "logo",
  ARROW = "arrow",
  DIAMOND = "diamond",
  LOGO_BACKGROUND = "logo-background",
  SYNTECH_HERO_TEXT = "syntech-hero-text",
  HERO_STAR = "hero-star",
  HERO_ARROW_LEFT = "hero-arrow-left",
  HERO_ARROW_RIGHT = "hero-arrow-right",
  SPANDOEKMAN_LOGO = "spandoekman-logo",
  REPUTY_LOGO = "reputy-logo",
  NETWRK_LOGO = "netwrk_logo",
  LUNE_CADEAU_LOGO = "lune_cadeau_logo",
  SOXEY_LOGO = "soxey_logo",
  QONSULTANT_LOGO = "qonsultant_logo",
  FACEDRIP_LOGO = "facedrip_logo",
  ELE_UZNACH_LOGO = "ele_uznach_logo",
  MENU = "menu",
  CLOSE = "close",
  DROPDOWN = "dropdown",
}
